language: node_js

node_js:
  - '8'
  - '9'

deploy:
  provider: npm
  email: nwoltman@outlook.com
  on:
    tags: true
  api_key:
    secure: hZPM7uLxcMHarRYh6AEDBY4jvIiAW6547Ge+Cog8XRfTeaMGFJpprXnlzUOV73hlqYF8ob6yisiavC/TJ+3gxsMsO3f/STBBMoeJjYcdYTIsvlimcCIRaLHdPiPy6TOHHtH+DBonf6nb6BVSkbBcjiVNkyc2hR0EhIvxuy3Huqq88Uc+HbqG+jUpSZI/I20GSqlAbGjQQxtqC8X/u7JGABACNNidnFUL5zBEzwJUE0JYXLz5ZG2RPh8Hj1agX2BQISIDqDMh6Am9LgiiZXscl7M8SvprQ5kIbIOPiK1wJ5I1BMskraxjebQiyedDKoEy8sJ5rvutCe6HIu6uSGWYdbbjlyYDrh7GDODMyzYS3kRxQ7x/cbjyXe7xvLa8kSmtzrIKJtTfs5WDTOA0vFLB9uihyKOC1N8vZA8NcmZXLiZRxsMSX70ZkHBI0AIpJvZGGLkYr44mI3cwDNPyyHL1Gv++mgVr7x+Ll7tNoXBhehehwMjf9X6GP6yMo6cTBo81Y7YhL0i0OITwZkLWPPutyCMI1A7Fl9q53qZVFZT+tpWFFxU0cTpT6yEkDuPaNF/JxOoFFj0u5aP+bPr+cG9p81SXxy6RLlP08KZOu/UiraAqH89JDadsmwTj1H83KSVM9XTzrnHMAKgInN1LFuZqO/bo9a9VbEdwI0cqIYJleIE=
